import Foundation

struct EvilCorpChallenge: Identifiable {
    let id: String; let title: String; let description: String; let difficulty: String
    let icon: String; let category: String; let cwe: String; let masvs: String; let maswe: String; let cvss: String
    let hints: [String]; let fridaSnippet: String

    static let all: [EvilCorpChallenge] = [
        EvilCorpChallenge(id:"userdefaults",title:"NSUserDefaults Storage",description:"Sensitive data in UserDefaults without encryption",difficulty:"Easy",icon:"gear",category:"Storage",cwe:"CWE-312",masvs:"STORAGE-1",maswe:"MASWE-0010",cvss:"5.0 (Medium)",
            hints:["Check the app's Preferences plist file","Look in Library/Preferences/ in the sandbox","Use plutil or objection ios nsuserdefaults get"],
            fridaSnippet:"// Dump NSUserDefaults\nvar NSUserDefaults = ObjC.classes.NSUserDefaults;\nvar dict = NSUserDefaults.standardUserDefaults().dictionaryRepresentation();\nconsole.log(JSON.stringify(dict, null, 2));"),
        EvilCorpChallenge(id:"keychain",title:"Keychain Misuse",description:"Keychain with kSecAttrAccessibleAlways",difficulty:"Easy",icon:"key",category:"Storage",cwe:"CWE-922",masvs:"STORAGE-1",maswe:"MASWE-0011",cvss:"6.8 (Medium)",
            hints:["kSecAttrAccessibleAlways is deprecated since iOS 9","Check accessibility flags in Keychain query","Use Keychain-Dumper on jailbroken device"],
            fridaSnippet:"// Dump keychain\nvar keychain = ObjC.classes.EvilCorp[\"- dumpKeychain\"];\n// objection -g com.evilcorp.ios run ios keychain dump"),
        EvilCorpChallenge(id:"plist",title:"Property List Files",description:"Secrets in plaintext plist files in Documents/",difficulty:"Easy",icon:"doc.text",category:"Storage",cwe:"CWE-312",masvs:"STORAGE-1",maswe:"MASWE-0010",cvss:"5.0 (Medium)",
            hints:["Look in app's Documents directory","Filenames: config.plist, sensitive_config.plist","Use plutil -p or SSH to read"],
            fridaSnippet:"// Read plist files\nvar paths = NSSearchPathForDirectoriesInDomains(9,1,true);\n// 9=NSDocumentDirectory, 1=NSUserDomainMask"),
        EvilCorpChallenge(id:"sqlite",title:"SQLite Injection",description:"Raw SQL queries concatenating user input — SQLi",difficulty:"Medium",icon:"cylinder",category:"Storage",cwe:"CWE-89",masvs:"STORAGE-1",maswe:"MASWE-0015",cvss:"7.5 (High)",
            hints:["Login uses string interpolation in SQL","Try: ' OR '1'='1' -- as username","UNION: ' UNION SELECT password,email,role FROM users --"],
            fridaSnippet:"// Hook sqlite3_prepare_v2\nvar sqlite3 = Module.findExportByName('libsqlite3.dylib','sqlite3_prepare_v2');\nInterceptor.attach(sqlite3,{onEnter:function(a){console.log('SQL:',Memory.readUtf8String(a[1]));}});"),
        EvilCorpChallenge(id:"jailbreak",title:"Jailbreak Detection",description:"Multiple jailbreak checks — bypass with Frida",difficulty:"Medium",icon:"lock.shield",category:"Auth",cwe:"CWE-693",masvs:"RESILIENCE-1",maswe:"MASWE-0095",cvss:"4.3 (Medium)",
            hints:["Checks are in JailbreakChallengeView.runChecks()","Path: /var/jb, /Applications/Cydia.app","URL schemes: cydia://, sileo://"],
            fridaSnippet:"// Bypass fileExistsAtPath\nvar NSFileManager = ObjC.classes.NSFileManager;\nInterceptor.attach(NSFileManager['- fileExistsAtPath:'].implementation,{onLeave(r){r.replace(ptr(0x0));}});"),
        EvilCorpChallenge(id:"sslpinning",title:"SSL Pinning Bypass",description:"Certificate pinning via URLSessionDelegate",difficulty:"Medium",icon:"shield",category:"Network",cwe:"CWE-295",masvs:"NETWORK-2",maswe:"MASWE-0061",cvss:"5.9 (Medium)",
            hints:["Delegate is SSLPinningDelegate","Compares cert hash against hardcoded value","Objection: ios sslpinning disable"],
            fridaSnippet:"// objection -g com.evilcorp.ios run ios sslpinning disable\n// Hook delegate\nvar d=ObjC.classes.SSLPinningDelegate;\nvar m=d['- urlSession:didReceiveChallenge:completionHandler:'];\nInterceptor.attach(m.implementation,{onEnter(a){var h=new ObjC.Block(a[4]);h.implementation(0,a[2]);}});"),
        EvilCorpChallenge(id:"webviewxss",title:"WebView XSS",description:"WKWebView JS+file access — XSS & local file read",difficulty:"Medium",icon:"globe",category:"Network",cwe:"CWE-79",masvs:"PLATFORM-2",maswe:"MASWE-0057",cvss:"6.1 (Medium)",
            hints:["JavaScript enabled + file access allowed","Try: javascript:alert(document.cookie)","Try: fetch('file:///etc/hosts')"],
            fridaSnippet:"// Hook WebView JS eval\nvar WKWebView=ObjC.classes.WKWebView;\nInterceptor.attach(WKWebView['- evaluateJavaScript:completionHandler:'].implementation,{onEnter(a){console.log('JS:',Memory.readUtf8String(a[2]));}});"),
        EvilCorpChallenge(id:"logging",title:"Insecure Logging",description:"Credentials logged via NSLog",difficulty:"Easy",icon:"terminal",category:"Storage",cwe:"CWE-532",masvs:"STORAGE-3",maswe:"MASWE-0005",cvss:"4.0 (Medium)",
            hints:["Search EVILCORP_AUTH in logs","idevicesyslog | grep EVILCORP","log stream --predicate 'process==EvilCorp'"],
            fridaSnippet:"// Hook NSLog\nvar NSLog = new NativeFunction(Module.findExportByName('Foundation','NSLog'),'void',['pointer','...']);"),
        EvilCorpChallenge(id:"hardcodedsecrets",title:"Hardcoded Secrets",description:"API keys embedded in binary — extract with strings/grep",difficulty:"Medium",icon:"eye.slash",category:"Storage",cwe:"CWE-798",masvs:"STORAGE-1",maswe:"MASWE-0062",cvss:"7.8 (High)",
            hints:["Use strings or grep on binary","Look for: AIza, sk_live, AKIA, EvilCorp_Super","grep -ao 'sk_live\\|AKIA\\|EvilCorp_Super' EvilCorp"],
            fridaSnippet:"// Scan binary for secrets\nProcess.enumerateModules().forEach(function(m){Memory.scan(m.base,m.size,'sk_live_',{onMatch(a){console.log('FOUND:',Memory.readUtf8String(a,80));}});});"),
        EvilCorpChallenge(id:"biometricbypass",title:"Biometric Bypass",description:"FaceID/TouchID client-only — bypass with Frida",difficulty:"Hard",icon:"faceid",category:"Auth",cwe:"CWE-287",masvs:"AUTH-1",maswe:"MASWE-0025",cvss:"6.8 (Medium)",
            hints:["LAContext.evaluatePolicy is client-side","No server validation","Hook reply block to force success"],
            fridaSnippet:"// Bypass biometric\nvar LAContext=ObjC.classes.LAContext;\nInterceptor.attach(LAContext['- evaluatePolicy:localizedReason:reply:'].implementation,{onEnter(a){var r=new ObjC.Block(a[4]);r.implementation(true,null);}});"),
        EvilCorpChallenge(id:"cryptography",title:"Broken Cryptography",description:"MD5 + AES-ECB + hardcoded key + XOR",difficulty:"Medium",icon:"lock.open",category:"Crypto",cwe:"CWE-327",masvs:"CRYPTO-1",maswe:"MASWE-0048",cvss:"7.5 (High)",
            hints:["MD5 cracked via hashcat/rainbow tables","AES-ECB key: 'evilcorpkey12345'","ECB: same input = same output (patterns leak)"],
            fridaSnippet:"// Hook CCCrypt\nvar CCCrypt=Module.findExportByName('CommonCrypto','CCCrypt');\nInterceptor.attach(CCCrypt,{onEnter(a){console.log('Key:',hexdump(a[3],{length:16}));console.log('Data:',hexdump(a[5]));}});"),
        EvilCorpChallenge(id:"network",title:"Insecure Network (HTTP)",description:"Cleartext HTTP with ATS disabled",difficulty:"Medium",icon:"antenna.radiowaves.left.and.right",category:"Network",cwe:"CWE-319",masvs:"NETWORK-1",maswe:"MASWE-0046",cvss:"6.5 (Medium)",
            hints:["ATS: NSAllowsArbitraryLoads=true","API uses HTTP not HTTPS","Credentials in cleartext POST body"],
            fridaSnippet:"// Hook URLSession\nvar NSURLSession=ObjC.classes.NSURLSession;\nInterceptor.attach(NSURLSession['- dataTaskWithRequest:'].implementation,{onEnter(a){var r=new ObjC.Object(a[2]);console.log('URL:',r.URL().absoluteString());console.log('Body:',r.HTTPBody().toString());}});"),
        EvilCorpChallenge(id:"urlscheme",title:"URL Scheme Hijacking",description:"evilcorp:// handler without validation",difficulty:"Medium",icon:"link",category:"Network",cwe:"CWE-939",masvs:"PLATFORM-2",maswe:"MASWE-0056",cvss:"6.5 (Medium)",
            hints:["App registers evilcorp:// URL scheme","evilcorp://login?user=admin&pass=hacked","evilcorp://transfer?to=attacker&amount=9999"],
            fridaSnippet:"// Hook URL open\nvar UIApplication=ObjC.classes.UIApplication;\nInterceptor.attach(UIApplication['- openURL:options:completionHandler:'].implementation,{onEnter(a){console.log('URL:',new ObjC.Object(a[2]).absoluteString());}});"),
        EvilCorpChallenge(id:"screenshot",title:"Screenshot Leakage",description:"Sensitive data visible in App Switcher",difficulty:"Easy",icon:"camera.viewfinder",category:"Storage",cwe:"CWE-200",masvs:"STORAGE-3",maswe:"MASWE-0042",cvss:"3.3 (Low)",
            hints:["No willResignActiveNotification handler","Press Home while viewing data","App Switcher shows unblurred snapshot"],
            fridaSnippet:"// Hook willResignActive to add blur\n// objection ios screen_protection enable"),
        EvilCorpChallenge(id:"antidebug",title:"Anti-Debugging Bypass",description:"Debugger/Frida detection via sysctl P_TRACED",difficulty:"Hard",icon:"ant.fill",category:"Auth",cwe:"CWE-693",masvs:"RESILIENCE-4",maswe:"MASWE-0096",cvss:"5.5 (Medium)",
            hints:["sysctl KERN_PROC checks P_TRACED flag","Also checks frida-server path","Bypass: hook sysctl to clear flags"],
            fridaSnippet:"// Bypass sysctl\nvar sysctl=Module.findExportByName(null,'sysctl');\nInterceptor.attach(sysctl,{onLeave(r){var kp=this.context.x1.add(32);var f=kp.add(0).readU32();kp.add(0).writeU32(f&~0x800);}});"),
        EvilCorpChallenge(id:"pasteboard",title:"Pasteboard Leakage",description:"UIPasteboard accessible by any app",difficulty:"Easy",icon:"doc.on.clipboard",category:"Storage",cwe:"CWE-200",masvs:"STORAGE-3",maswe:"MASWE-0042",cvss:"2.4 (Low)",
            hints:["UIPasteboard.general is system-wide","Copy sensitive data then check pasteboard","Any app can read clipboard"],
            fridaSnippet:"// Monitor pasteboard\nvar UIPasteboard=ObjC.classes.UIPasteboard;\nvar pb=UIPasteboard.generalPasteboard();\nconsole.log('Clipboard:',pb.string().toString());"),
        EvilCorpChallenge(id:"filesharing",title:"iTunes File Sharing",description:"UIFileSharingEnabled — files via USB no auth",difficulty:"Medium",icon:"square.and.arrow.up",category:"Storage",cwe:"CWE-200",masvs:"STORAGE-2",maswe:"MASWE-0010",cvss:"4.6 (Medium)",
            hints:["UIFileSharingEnabled=true in Info.plist","USB → Finder → Files → EvilCorp","Documents/ fully accessible"],
            fridaSnippet:"// List Documents\nvar paths=NSSearchPathForDirectoriesInDomains(9,1,true);\nvar docs=paths.firstObject().toString();\nvar fm=ObjC.classes.NSFileManager.defaultManager();\nconsole.log(fm.contentsOfDirectoryAtPath_error_(docs,null).toString());"),
        EvilCorpChallenge(id:"keyboard",title:"Keyboard Cache Leak",description:"Autocorrect caches TextField input",difficulty:"Easy",icon:"keyboard",category:"Storage",cwe:"CWE-200",masvs:"STORAGE-3",maswe:"MASWE-0042",cvss:"2.4 (Low)",
            hints:["Plain TextField (not SecureField) caches input","Keyboard cache: Library/Keyboard/*.dat","Forensic tools can recover"],
            fridaSnippet:"// Hook UITextField\nvar UITextField=ObjC.classes.UITextField;\nInterceptor.attach(UITextField['- setText:'].implementation,{onEnter(a){console.log('Text:',Memory.readUtf8String(a[2]));}});"),
        EvilCorpChallenge(id:"binarypatch",title:"Binary Patching",description:"Patch runtime checks via Hopper/IDA",difficulty:"Hard",icon:"hammer.fill",category:"Crypto",cwe:"CWE-1275",masvs:"RESILIENCE-4",maswe:"MASWE-0096",cvss:"6.5 (Medium)",
            hints:["checkLicense() and checkPremium() in binary","Open in Hopper/IDA Pro","Change MOV X0,#0 → MOV X0,#1 ; RET"],
            fridaSnippet:"// Frida bypass\nvar checkL=Module.findExportByName(null,'checkLicense');\nInterceptor.attach(checkL,{onLeave(r){r.replace(ptr(0x1));}});\n// Flag: EVILCORP{B1N4RY_P4TCH1NG_M4ST3R}"),
        EvilCorpChallenge(id:"pinbruteforce",title:"Vulnerable Vault (PIN)",description:"4-digit PIN no rate limit — brute force 10K combos",difficulty:"Hard",icon:"lock.fill",category:"Auth",cwe:"CWE-307",masvs:"AUTH-1",maswe:"MASWE-0025",cvss:"7.5 (High)",
            hints:["4-digit PIN (0000-9999)","No rate limiting or lockout","Brute force all 10000 combinations"],
            fridaSnippet:"// Auto brute force\nfor(var i=0;i<10000;i++){var pin=String(i).padStart(4,'0');console.log('Trying:',pin);}"),
        EvilCorpChallenge(id:"urlcache",title:"NSURLSession Cache",description:"HTTP responses cached in Cache.db",difficulty:"Medium",icon:"arrow.down.doc",category:"Network",cwe:"CWE-200",masvs:"STORAGE-3",maswe:"MASWE-0010",cvss:"5.0 (Medium)",
            hints:["NSURLCache with 100MB disk capacity","Cache at: Library/Caches/Cache.db","sqlite3 Cache.db .dump | grep token"],
            fridaSnippet:"// Dump cache\nvar cache=ObjC.classes.NSURLCache.sharedURLCache();\nvar req=ObjC.classes.NSURLRequest.requestWithURL_(ObjC.classes.NSURL.URLWithString_('https://api.evilcorp.local/user/profile'));\nvar resp=cache.cachedResponseForRequest_(req);\nif(resp)console.log(resp.data().toString());"),
        EvilCorpChallenge(id:"excessiveperms",title:"Excessive Permissions",description:"5 privacy permissions abused — contacts dumped",difficulty:"Medium",icon:"exclamationmark.shield.fill",category:"Storage",cwe:"CWE-863",masvs:"PLATFORM-1",maswe:"MASWE-0098",cvss:"5.5 (Medium)",
            hints:["Requests Camera,Mic,Contacts,Photos,Location","No actual camera/mic feature exists","Contacts: idevicesyslog | grep CONTACT_DUMP"],
            fridaSnippet:"// Monitor contact access\nvar CNContactStore=ObjC.classes.CNContactStore;\nInterceptor.attach(CNContactStore['- enumerateContactsWithFetchRequest:error:usingBlock:'].implementation,{onEnter(){console.log('Contacts accessed!');}});"),
        EvilCorpChallenge(id:"phishing",title:"Phishing & UI Redressing",description:"Fake alerts + overlay attacks + URL phishing",difficulty:"Medium",icon:"exclamationmark.triangle.fill",category:"Network",cwe:"CWE-1021",masvs:"PLATFORM-2",maswe:"MASWE-0099",cvss:"6.5 (Medium)",
            hints:["Fake alert mimics system security warning","Overlay hides legitimate content with fake login","evilcorp://login?user=victim&pass=stolen"],
            fridaSnippet:"// Hook UIAlertController\nvar UIAlertController=ObjC.classes.UIAlertController;\nInterceptor.attach(UIAlertController['- addTextFieldWithConfigurationHandler:'].implementation,{onEnter(){console.log('Alert with text field!');}});"),
        EvilCorpChallenge(id:"memorysensitive",title:"Memory Sensitive Data",description:"Secrets in static vars — Frida memory scan",difficulty:"Hard",icon:"memorychip",category:"Storage",cwe:"CWE-316",masvs:"STORAGE-3",maswe:"MASWE-0043",cvss:"6.8 (Medium)",
            hints:["Secrets as static let/var in Swift structs","Never cleared from memory after use","Frida Process.enumerateRanges + Memory.scan"],
            fridaSnippet:"// Memory scan\nvar patterns=['sk_live_evilcorp_memory','Bearer eyJ','EvilCorp.DB.Master'];\nProcess.enumerateRanges({protection:'r--',coalesce:true},{onMatch(r){patterns.forEach(function(p){Memory.scan(r.base,r.size,p,{onMatch(a){console.log('FOUND:',Memory.readUtf8String(a,100));}});});},onComplete(){console.log('Done');}});"),
        EvilCorpChallenge(id:"xpc",title:"XPC/IPC Communication",description:"Unauthenticated XPC services expose data",difficulty:"Hard",icon:"arrow.triangle.branch",category:"Network",cwe:"CWE-306",masvs:"PLATFORM-2",maswe:"MASWE-0056",cvss:"7.5 (High)",
            hints:["5 XPC services without authentication","Services: auth,data-sync,payment-handler","Any process can connect and call methods"],
            fridaSnippet:"// Hook NSXPCConnection\nvar NSXPCConnection=ObjC.classes.NSXPCConnection;\nInterceptor.attach(NSXPCConnection['- initWithMachServiceName:'].implementation,{onEnter(a){console.log('XPC:',Memory.readUtf8String(a[2]));}});"),
        EvilCorpChallenge(id:"localdata",title:"Local Data Storage",description:"7 sub-categories: UserDefaults, Plist, Keychain, SQLite, Cache, Pasteboard, Keyboard",difficulty:"Easy",icon:"externaldrive.fill",category:"Storage",cwe:"CWE-312",masvs:"STORAGE-1",maswe:"MASWE-0010",cvss:"5.0 (Medium)",
            hints:["Explore all 7 sub-tabs","Each stores sensitive data differently","Check: plist, sqlite, keychain, cache, clipboard"],
            fridaSnippet:"// Dump all local storage\n// UserDefaults: ios nsuserdefaults get\n// Keychain: ios keychain dump\n// Cache: sqlite3 Cache.db .dump"),
        EvilCorpChallenge(id:"deviceinfo",title:"Device Intelligence",description:"iOS device info: model, iOS version, jailbreak status, sandbox path",difficulty:"Easy",icon:"iphone.gen3",category:"Storage",cwe:"CWE-200",masvs:"STORAGE-3",maswe:"MASWE-0042",cvss:"2.0 (Low)",
            hints:["Check the device info tab","Shows: model, iOS version, jailbreak status","Also: sandbox path, screen size, PID"],
            fridaSnippet:"// Get device info via Frida\nObjC.classes.UIDevice.currentDevice();\n// model, systemVersion, name, identifierForVendor"),

        EvilCorpChallenge(id:"randomgen",title:"Weak Random Generation",description:"arc4random/rand for tokens — predictable",difficulty:"Medium",icon:"dice.fill",category:"Crypto",cwe:"CWE-338",masvs:"CRYPTO-1",maswe:"MASWE-0048",cvss:"6.5 (Medium)",
            hints:["arc4random() and rand() are NOT cryptographically secure","Predictable tokens enable session hijacking","Use SecRandomCopyBytes for security tokens"],
            fridaSnippet:"// Hook arc4random\nvar arc4random=Module.findExportByName('libsystem_c.dylib','arc4random');\nInterceptor.attach(arc4random,{onLeave(r){console.log('rand:',r.toInt32());}});"),
        EvilCorpChallenge(id:"pathtraversal",title:"Path Traversal",description:"File paths from user input — read arbitrary files",difficulty:"Hard",icon:"folder.badge.questionmark",category:"Storage",cwe:"CWE-22",masvs:"PLATFORM-2",maswe:"MASWE-0056",cvss:"7.5 (High)",
            hints:["File path built from user input without sanitization","Try: ../etc/hosts or ../../etc/passwd","No allow-list or path validation"],
            fridaSnippet:"// Hook NSFileManager reads\nvar NSFileManager=ObjC.classes.NSFileManager;\nInterceptor.attach(NSFileManager['- contentsAtPath:'].implementation,{onEnter(a){console.log('Read:',Memory.readUtf8String(a[2]));}});"),
        EvilCorpChallenge(id:"bgfetch",title:"Background Fetch Leak",description:"Sensitive data cached during background refresh — plaintext on disk",difficulty:"Medium",icon:"clock.arrow.2.circlepath",category:"Storage",cwe:"CWE-312",masvs:"STORAGE-3",maswe:"MASWE-0010",cvss:"5.5 (Medium)",
            hints:["Background fetch caches sensitive data to Documents/","No encryption at rest","Accessible via iTunes File Sharing (USB)"],
            fridaSnippet:"// Monitor background fetch\n// Hook UIApplicationDelegate background fetch\n// Check: cat Documents/background_fetch_cache.dat"),
    ]

}
